---
# this has only been tested with an archlinux system. Run at your own
# risk otherwise.
- name: Install headscale
  hosts: headscale
  remote_user: pat
  pre_tasks:
    - name: Email?
      ansible.builtin.fail:
        msg: distinct lack of email
      when: headscale.acme_email == "idk"
    - name: Hostname?
      ansible.builtin.fail:
        msg: distinct lack of hostname
      when: headscale.hostname is undefined or headscale.hostname == "idk"
    - name: Systemd?
      ansible.builtin.fail:
        msg: you need systemd sorry goodbye
      when: ansible_facts.service_mgr != "systemd"
  tasks:
    ## packages
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      become: true

    - name: Install podman
      ansible.builtin.package:
        name: podman
        state: present
      become: true


    ## headscale config
    - name: Create dirs
      ansible.builtin.file:
        path: '/home/{{ ansible_user }}/headscale/{{ item }}'
        state: directory
        mode: '0755'
      with_items:
        - config
        - lib
        - run

    - name: Headscale config
      ansible.builtin.template:
        src: headscale/config.yaml
        dest: '/home/{{ ansible_user }}/headscale/config/config.yaml'
        mode: '0644'

    - name: Install headscale .container systemd unit
      ansible.builtin.copy:
        src: headscale/headscale.container
        dest: '/home/{{ ansible_user }}/.config/containers/systemd/headscale.container'
        mode: '0644'


    ## nginx config
    - name: Install nginx conf
      ansible.builtin.copy:
        src: headscale/headscale-acme-redirect.conf
        dest: /etc/nginx/conf.d/headscale-acme-redirect.conf
        mode: '0644'
      become: true
    - name: Create http static dir
      ansible.builtin.file:
        path: /srv/http
        state: directory
        mode: '0755'
    - name: Install robots.txt
      ansible.builtin.copy:
        src: headscale/robots.txt
        dest: /srv/http
        mode: '0644'
      become: true


    ## services
    - name: Start nginx
      become: true
      ansible.builtin.systemd_service:
        name: nginx
        enabled: true
        state: started

    - name: Enable Linger
      become: true
      ansible.builtin.command: 'loginctl enable-linger {{ ansible_user }}'
      args:
        creates: '/var/lib/systemd/linger/{{ ansible_user }}'

    # move to handler please
    - name: Activate systemd service
      ansible.builtin.systemd_service:
        scope: user
        name: headscale.service
        state: started
        enabled: true
        daemon_reload: true
