apiVersion: v1
kind: Service
metadata:
  name: opencode
  namespace: kubevirt
  labels:
    app.kubernetes.io/name: opencode
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/domain: opencode
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
    - name: node-exporter
      port: 9100
      targetPort: 9100
      protocol: TCP