apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "homelab-deploy.fullname" . }}-kubevirt-cr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/depends-on: '[{{ include "homelab-deploy.fullname" . }}-kubevirt]'
  labels:
    {{- include "homelab-deploy.labels" . | nindent 4 }}
spec:
  project: default

  source:
    repoURL: https://github.com/spigwitmer/homelab-stuff.git
    targetRevision: HEAD
    path: kubevirt
    directory:
      include: '{kubevirt-cr.yaml}'

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubevirt

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true