apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: camtap@fastmail.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    # ACME DNS-01 provider configurations
    solvers:
    - selector:
        dnsZones:
        - 'camtap.io'
      dns01:
        webhook:
          solverName: linode
          groupName: home.camtap.io
          config:
            apiKeySecretRef:
              name: linode-credentials
              key: token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: camtap@fastmail.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod

    # ACME DNS-01 provider configurations
    solvers:
    - selector:
        dnsZones:
        - 'camtap.io'
      dns01:
        webhook:
          solverName: linode
          groupName: home.camtap.io
          config:
            apiKeySecretRef:
              name: linode-credentials
              key: token
